### ISSUE TITLE
Plugin doesn't recognize word under cursor properly

### ISSUE THREAD

**Issue by petRUShka** [sunaku/vim-dasht#7] opened 2017-04-11 08:29 UTC
Suppose I have following code in Ruby:

```
@answers.rotate!(rand(3))
```

I place my cursor in the middle of the word `rotate`:

```
@answers.rot<|>ate!(rand(3))
```

where `<|>` is the position of cursor. And then I press `<Leader> K` configured as in your README.

After pressing the key I see documentation on `rand` and not on `rotate!` which I expected.

**Comment by sunaku** [comment] 2017-04-12 18:39
This happens because we currently only [split function calls on parentheses]( https://github.com/sunaku/vim-dasht/blob/31d0586ec4e3c37cedcfeca66c59e53a0eba77ae/t/dasht_test.vim#L92-L100 ), ignoring OOP dot notation. :neckbeard:

To support OOP dot notation, the "dot" might be language-specific :fearful: so I'm thinking of doing this in a language-agnostic way using Vim's `iskeyword` setting to tell me which characters are safe to split on. :camel:

**Comment by petRUShka** [comment] 2017-04-12 21:16
`iskeyword` is probably the solution. But honestly I always thought that VimL has its own built-in function for `word under cursor`, hasn't it?

**Comment by sunaku** [comment] 2017-04-13 00:09
Yes, we already use Vim's built-in `<cword>` facility for this purpose. :+1:  And here is the root cause:

```vim
nnoremap <silent> <Leader>K :call Dasht([expand('<cWORD>'), expand('<cword>')])<Return>
```

The mapping searches for cWORD **first _and then_** falls back to searching cword, which is the opposite of what you  want. :face_with_head_bandage:  I don't remember why I chose this particular order, but it feels counter-intuitive now.

This issue can be solved by changing the order of cwords in the above mapping to this:

```vim
nnoremap <silent> <Leader>K :call Dasht([expand('<cword>'), expand('<cWORD>')])<Return>
```

**Comment by sunaku** [comment] 2017-04-13 00:19
README has been updated accordingly. :books:  Thanks for reporting this issue. :+1:  Closing.

**Closed as completed by sunaku** 2017-04-13 00:19 UTC
Labels: question
